### PR TITLE
Pretty print result from playground

### PR DESCRIPTION
**Pull request by fee1-dead**

### CODE REVIEW

**Comment by kangalioo** [comment]
Sorry for late reply, I forgot 😅 

The Rust community server prefers not to do this 
image

**Comment by fee1-dead** [comment]
Well, then could there be another command that does pretty print? Like `?evalpp`?

**Comment by kangalioo** [comment]
`?play println!("{:#?}", value)` still works. Do you pretty-print so often that a specialized command is worth it?

**Comment by fee1-dead** [comment]
That's fine, I guess `?play dbg!(v)` would also work.

**Pull request closed without merging**
